title: title
email: your_mail
description: >- # this means to ignore newlines until "baseurl:"
  Description of your website.
# baseurl: "/spirunilazur" # the subpath of your site, e.g. /blog
url: "url of your website" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: YYY
github_username: YYY

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

# we don't want to track all this shit ***
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
